/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testDll_OCR */

#ifndef _Included_testDll_OCR
#define _Included_testDll_OCR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testDll_OCR
 * Method:    GetChar
 * Signature: ([FI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_testDll_OCR_GetChar
  (JNIEnv *, jobject, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
