/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mhd_OCR */

#ifndef _Included_mhd_OCR
#define _Included_mhd_OCR
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     mhd_OCR
 * Method:    SayHello
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_mhd_OCR_SayHello(JNIEnv *, jobject);

  /*
 * Class:     mhd_OCR
 * Method:    GetChar
 * Signature: ([FI)Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_mhd_OCR_GetChar(JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
